default["logstash-forwarder"]["version"]                    = "0.3.1"
default["logstash-forwarder"]["user"]                       = "logstash-forwarder"
default["logstash-forwarder"]["group"]                      = "logstash-forwarder"
default["logstash-forwarder"]["dir"]                        = "/opt/logstash-forwarder"
default["logstash-forwarder"]["log_dir"]                    = "/var/log/logstash-forwarder"
default["logstash-forwarder"]["hosts"]                      = [ "localhost" ]
default["logstash-forwarder"]["port"]                       = "6060"
default["logstash-forwarder"]["timeout"]                    = "15"
default["logstash-forwarder"]["ssl_certificate_path"]       = "/etc/logstash-forwarder/logstash-forwarder.crt"
default["logstash-forwarder"]["ssl_key_path"]               = "/etc/logstash-forwarder/logstash-forwarder.key"
default["logstash-forwarder"]["ssl_ca_certificate_path"]    = "/etc/logstash-forwarder/logstash-forwarder.crt"
default["logstash-forwarder"]["files"]                      = { "syslog" => [ "/var/log/syslog" ]}
default["logstash-forwarder"]["logstash_role"]              = "logstash"
default["logstash-forwarder"]["logstash_fqdn"]              = ""
default["logstash-forwarder"]["config_file"]                = "/etc/logstash-forwarder/logstash-forwarder.conf"
